"""
tests/test_doc_facts.py

scripts/doc_facts.py generates README.md's status table. Found by the full review:
the README said "11 companies" (16 loaded), "192 tests" in two places and "87 tests" in
a third (300+), "62 flags" (69). No database needed: rendering and block replacement are
pure, and the lint at the bottom reads README.md itself so hand-typed counts cannot creep
back in without failing CI.
"""
import re
from pathlib import Path

import pytest

README = Path(__file__).parent.parent / "README.md"


@pytest.fixture(scope="module")
def df(load_script):
    return load_script("doc_facts.py")


def facts(**over):
    base = {
        "as_of": "2026-09-19", "n_companies": 16, "company_names": ["A", "B"], "countries": ["France", "Italy"],
        "n_facts": 15112, "years_min": 3, "years_max": 8, "years_median": 5.5, "year_first": 2017, "year_last": 2025,
        "n_ratio_names": 12, "n_ratio_values": 681, "n_ratio_blank": 303,
        "coverage": {"Trading comps": 11, "3-statement model": 9, "DCF valuation": 9, "Market risk": 11,
                     "Credit profile": 11, "Ratio forecasts": 9, "Forecast backtest": 9},
        "n_flags": 69, "flags_by_severity": {"high": 27, "medium": 13, "low": 29}, "n_flagged_companies": 13,
        "universe_total": 156, "universe_snapshots": 4, "universe_as_of": "2026-09-17", "universe_linked": 0,
        "tests_total": 305, "tests_passed": 271, "tests_skipped": 34,
    }
    base.update(over)
    return base


README_TEXT = (
    "intro\r\n<!-- FACTS:BEGIN (generated by scripts/doc_facts.py - do not edit by hand; run it with --write) -->\r\n"
    "| | |\r\n|---|---|\r\n| Facts in database | 1 |\r\n<!-- FACTS:END -->\r\noutro\r\n"
)


class TestRendering:
    def test_rows_carry_the_measured_numbers(self, df):
        d = dict(df.build_rows(facts()))
        assert d["Facts in database"] == "15,112"
        assert d["Trading comps"] == "11/16 companies"
        assert d["Forensics flags"].startswith("69 across 13 companies (27 high / 13 medium / 29 low")
        assert d["Tests"].startswith("305 (271 run in CI without a database, 34 need a live database")
        assert "156 distinct entities over 4 snapshots" in d["Candidate universe"]

    def test_a_missing_severity_counts_as_zero_not_a_crash(self, df):
        d = dict(df.build_rows(facts(flags_by_severity={"high": 2})))
        assert "2 high / 0 medium / 0 low" in d["Forensics flags"]

    def test_render_is_a_two_column_markdown_table(self, df):
        t = df.render_table([("a", "1"), ("b", "2")])
        assert t.splitlines() == ["| | |", "|---|---|", "| a | 1 |", "| b | 2 |"]


class TestBlockReplacement:
    def test_only_the_block_changes_and_line_endings_survive(self, df):
        new = df.replace_block(README_TEXT, df.render_table([("Facts in database", "2")]))
        assert new.startswith("intro\r\n") and new.endswith("<!-- FACTS:END -->\r\noutro\r\n")
        assert "| Facts in database | 2 |" in new and "| Facts in database | 1 |" not in new
        assert "\r\n" in new and re.search(r"(?<!\r)\n", new) is None, "mixed line endings"

    def test_it_is_idempotent(self, df):
        table = df.render_table([("Facts in database", "2")])
        once = df.replace_block(README_TEXT, table)
        assert df.replace_block(once, table) == once

    def test_missing_markers_raise_instead_of_silently_doing_nothing(self, df):
        with pytest.raises(ValueError, match="markers"):
            df.replace_block("no markers here", "| | |\n")


class TestDriftDetection:
    def table(self, df, n):
        return df.render_table([("Measured on", "2026-01-01"), ("Facts in database", str(n))])

    def test_a_different_number_is_drift(self, df):
        text = df.replace_block(README_TEXT, self.table(df, 1))
        assert df.differs(text, self.table(df, 2))

    def test_the_date_row_alone_is_not_drift(self, df):
        text = df.replace_block(README_TEXT, self.table(df, 1))
        other_day = df.render_table([("Measured on", "2027-12-31"), ("Facts in database", "1")])
        assert not df.differs(text, other_day)

    def test_the_test_count_alone_is_not_drift_but_other_rows_are(self, df):
        """The count moves with every PR that adds a test; gating on it would keep --check red."""
        def table(tests, comps):
            return df.render_table([("Measured on", "d"), ("Trading comps", comps), ("Tests", tests)])
        text = df.replace_block(README_TEXT, table("305 (...)", "11/16 companies"))
        assert not df.differs(text, table("317 (...)", "11/16 companies"))
        assert df.differs(text, table("305 (...)", "12/16 companies"))

    def test_a_readme_without_the_block_counts_as_drift(self, df):
        assert df.differs("nothing", self.table(df, 1))


@pytest.fixture(scope="module")
def text():
    return README.read_text(encoding="utf-8")


class TestTheRealReadme:
    """Reads README.md itself (no database): the guard that hand-typed status numbers cannot return."""

    def test_it_has_exactly_one_generated_block(self, text):
        assert text.count("<!-- FACTS:BEGIN") == 1 and text.count("<!-- FACTS:END -->") == 1

    def test_the_block_has_every_row_the_generator_produces(self, df, text):
        block = df.current_block(text)
        for label, _ in df.build_rows(facts()):
            assert f"| {label} |" in block, label

    def test_no_hand_typed_test_or_company_counts_outside_the_block(self, text):
        outside = re.sub(r"<!-- FACTS:BEGIN.*?<!-- FACTS:END -->", "", text, flags=re.S)
        bad = re.findall(r"\b\d+\s+(?:pytest\s+)?(?:regression\s+)?tests\b|\b\d+\s+European listed companies\b", outside)
        assert not bad, f"hand-typed counts that will go stale - point at the status table instead: {bad}"
