"""
scripts/doc_facts.py

WHAT
----
Generates the README's "Current status" table from the database and the test suite,
so no number in it is typed by hand.

WHY: found by the full review - the README said "11 companies" (16 are loaded),
"192 tests" in two places and "87 tests" in a third (the suite has 300+),
"62 flags" (66), and "7/11" for the resolver. Hand-typed status numbers go stale
the day after they are written; a generated block cannot, as long as someone can
notice when it has.

USAGE
-----
    python scripts/doc_facts.py            # print the table, change nothing
    python scripts/doc_facts.py --write    # rewrite the block between the README markers
    python scripts/doc_facts.py --check    # exit 1 if the README's block differs from reality

The block lives between `<!-- FACTS:BEGIN ... -->` and `<!-- FACTS:END -->` in README.md.
`--check` ignores the "Measured on" row (a date) and the "Tests" row (its count changes
whenever any PR adds a test); every other row must match the database exactly.

Needs DATABASE_URL (it reads the live database, read-only) and runs the test
suite once with the database disabled to count tests the way CI sees them.
"""
import argparse
import os
import re
import statistics
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
README = ROOT / "README.md"
BEGIN = "<!-- FACTS:BEGIN (generated by scripts/doc_facts.py - do not edit by hand; run it with --write) -->"
END = "<!-- FACTS:END -->"
BLOCK_RE = re.compile(re.escape(BEGIN[:len("<!-- FACTS:BEGIN")]) + r".*?-->\r?\n(.*?)" + re.escape(END), re.S)

# analysis tables that carry company_id -> label shown in the README
COVERAGE_TABLES = [
    ("valuation", "Trading comps"),
    ("three_statement_projection", "3-statement model"),
    ("dcf_valuation", "DCF valuation"),
    ("market_risk", "Market risk"),
    ("credit_profile", "Credit profile"),
    ("forecast", "Ratio forecasts"),
    ("backtest", "Forecast backtest"),
]


# ---------------------------------------------------------------- rendering (pure)

def build_rows(f: dict) -> list:
    """[(label, value)] from a facts dict. Pure - no I/O."""
    n = f["n_companies"]
    rows = [
        ("Measured on", f["as_of"]),
        ("Companies loaded", f"{n}: {', '.join(f['company_names'])}"),
        ("Countries", ", ".join(f["countries"])),
        ("Facts in database", f"{f['n_facts']:,}"),
        ("Years with ratios, per company", f"{f['years_min']}-{f['years_max']} (median {f['years_median']:g}); "
                                           f"calendar span {f['year_first']}-{f['year_last']}"),
        ("Ratios computed", f"{f['n_ratio_names']} distinct ratios: {f['n_ratio_values']:,} values, "
                            f"{f['n_ratio_blank']:,} blank (an input is missing or the ratio is not meaningful "
                            f"for that company - stored blank, never as zero)"),
    ]
    for _, label in COVERAGE_TABLES:
        rows.append((label, f"{f['coverage'][label]}/{n} companies"))
    rows += [
        ("Forensics flags", f"{f['n_flags']} across {f['n_flagged_companies']} companies "
                            f"({f['flags_by_severity'].get('high', 0)} high / "
                            f"{f['flags_by_severity'].get('medium', 0)} medium / "
                            f"{f['flags_by_severity'].get('low', 0)} low severity)"),
        ("Candidate universe", f"{f['universe_total']} distinct entities over {f['universe_snapshots']} snapshots "
                               f"(latest {f['universe_as_of']}); {f['universe_linked']} linked to a loaded company"),
        ("Tests", f"{f['tests_total']} ({f['tests_passed']} run in CI without a database, "
                  f"{f['tests_skipped']} need a live database and skip there)"),
    ]
    return rows


def render_table(rows: list) -> str:
    lines = ["| | |", "|---|---|"] + [f"| {a} | {b} |" for a, b in rows]
    return "\n".join(lines) + "\n"


def replace_block(text: str, table: str) -> str:
    """README text with the generated block replaced. Raises if the markers are missing."""
    if not BLOCK_RE.search(text):
        raise ValueError("README has no FACTS:BEGIN / FACTS:END markers")
    nl = "\r\n" if "\r\n" in text else "\n"
    body = table.replace("\n", nl)
    return BLOCK_RE.sub(lambda m: BEGIN + nl + body + END, text, count=1)


def current_block(text: str):
    m = BLOCK_RE.search(text)
    return None if not m else m.group(1)


CHURNING_ROWS = ("| Measured on |", "| Tests |")


def comparable(table: str) -> str:
    """The table minus the rows that change on every commit (the date, and the test count -
    it moves whenever any PR adds a test, so gating on it would keep --check permanently red).
    Every other row must match reality. The README's "Measured on" row dates the whole table."""
    lines = table.replace("\r\n", "\n").splitlines()
    return "\n".join(line for line in lines if not line.startswith(CHURNING_ROWS)).strip()


def differs(text: str, table: str) -> bool:
    cur = current_block(text)
    return cur is None or comparable(cur) != comparable(table)


# ---------------------------------------------------------------- measuring

def count_tests() -> dict:
    """Runs pytest once with the database disabled (DATABASE_URL set to empty so load_dotenv
    cannot re-enable it) and reads its summary line - the numbers CI sees."""
    env = dict(os.environ, DATABASE_URL="")
    out = subprocess.run([sys.executable, "-m", "pytest", "tests", "-q", "-p", "no:cacheprovider"],
                         cwd=ROOT, env=env, capture_output=True, text=True, timeout=600).stdout
    m = re.search(r"(\d+) passed(?:, (\d+) skipped)?", out)
    if not m or " failed" in out.splitlines()[-1]:
        raise RuntimeError("could not read a clean pytest summary:\n" + "\n".join(out.splitlines()[-5:]))
    passed, skipped = int(m.group(1)), int(m.group(2) or 0)
    return {"tests_passed": passed, "tests_skipped": skipped, "tests_total": passed + skipped}


def collect_facts(engine) -> dict:
    import datetime

    from sqlalchemy import text
    with engine.connect() as c:
        def one(sql):
            return c.execute(text(sql)).scalar()

        names = [r[0] for r in c.execute(text("SELECT name FROM company ORDER BY name"))]
        countries = sorted(r[0] for r in c.execute(text("SELECT DISTINCT country FROM company WHERE country IS NOT NULL")))
        per_company_years = [r[0] for r in c.execute(text(
            "SELECT COUNT(DISTINCT year) FROM ratio GROUP BY company_id"))]
        coverage = {label: one(f"SELECT COUNT(DISTINCT company_id) FROM {table}") for table, label in COVERAGE_TABLES}
        sev = {r[0]: r[1] for r in c.execute(text("SELECT severity, COUNT(*) FROM forensics_flag GROUP BY 1"))}
        uni_as_of = one("SELECT MAX(as_of) FROM universe_membership")
        facts = {
            "as_of": datetime.date.today().isoformat(),
            "n_companies": len(names), "company_names": names, "countries": countries,
            "n_facts": one("SELECT COUNT(*) FROM fact_value"),
            "years_min": min(per_company_years), "years_max": max(per_company_years),
            "years_median": statistics.median(per_company_years),
            "year_first": one("SELECT MIN(year) FROM ratio"), "year_last": one("SELECT MAX(year) FROM ratio"),
            "n_ratio_names": one("SELECT COUNT(DISTINCT ratio_name) FROM ratio"),
            "n_ratio_values": one("SELECT COUNT(*) FROM ratio WHERE value IS NOT NULL"),
            "n_ratio_blank": one("SELECT COUNT(*) FROM ratio WHERE value IS NULL"),
            "coverage": coverage,
            "n_flags": sum(sev.values()), "flags_by_severity": sev,
            "n_flagged_companies": one("SELECT COUNT(DISTINCT company_id) FROM forensics_flag"),
            # distinct ENTITIES across all snapshots: a snapshot can be a partial re-scan (the
            # 2026-09-17 one holds 21 rows), so "rows in the latest snapshot" is not the universe
            "universe_as_of": str(uni_as_of),
            "universe_total": one("SELECT COUNT(DISTINCT entity_identifier) FROM universe_membership"),
            "universe_snapshots": one("SELECT COUNT(DISTINCT as_of) FROM universe_membership"),
            "universe_linked": one("SELECT COUNT(DISTINCT entity_identifier) FROM universe_membership "
                                   "WHERE company_id IS NOT NULL"),
        }
    facts.update(count_tests())
    return facts


# ---------------------------------------------------------------- main

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="rewrite the block in README.md")
    mode.add_argument("--check", action="store_true", help="exit 1 if the README block is out of date")
    args = ap.parse_args()

    from dotenv import load_dotenv
    from sqlalchemy import create_engine
    load_dotenv()
    if not os.environ.get("DATABASE_URL"):
        print("DATABASE_URL not found. Check your .env file.")
        sys.exit(1)
    table = render_table(build_rows(collect_facts(create_engine(os.environ["DATABASE_URL"], pool_pre_ping=True))))

    # newline="" both ways: the README's own line endings (CRLF on Windows checkouts) must survive
    with open(README, encoding="utf-8", newline="") as fh:
        text_ = fh.read()
    if args.write:
        with open(README, "w", encoding="utf-8", newline="") as fh:
            fh.write(replace_block(text_, table))
        print("README block rewritten.")
    elif args.check:
        if differs(text_, table):
            print("README's status block is OUT OF DATE. Regenerated table:\n\n" + table)
            print("Run: python scripts/doc_facts.py --write")
            sys.exit(1)
        print("README's status block matches reality.")
    else:
        print(table)
